### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chmonyasik** [Elephant1214/LetMeTeleport#1]
Hello! Sorry, this is not a bug but a question, I wonder how this works, does it just remove the console spam or fix the problem? Your mod can work together with toofast (https://www.curseforge.com/minecraft/mc-mods/too-fast), and in our case toofast does not remove the error from the console

**Comment by chmonyasik** [comment]
also there are:

https://www.curseforge.com/minecraft/mc-mods/gotta-go-fast

https://modrinth.com/mod/gotta-go-fast-fabric (same name, other author)

https://modrinth.com/mod/just-enough-speed

**Comment by Elephant1214** [comment]
> Hello! Sorry, this is not a bug but a question, I wonder how this works, does it just remove the console spam or fix the problem? Your mod can work together with toofast (https://www.curseforge.com/minecraft/mc-mods/too-fast), and in our case toofast does not remove the error from the console

The problem is really that Mojang didn't implement their fix for the console spam correctly. Teleporting and causing it really is correct with how you teleport in Minecraft. Mojang added a field so that they could handle it, but it gets reset too early and it seems like they forgot that the server couldn't receive and handle the response packet(s) until after the method execution.

Considering Too Fast just increases the maximum movement speed, it makes sense. Let Me Teleport basically keeps a list of players who are teleporting and injects into the player move handler to set the field Mojang added to true which causes it to skip the entire movement speed check when a player is teleporting. The player move handler is where teleports are actually handled when the player finally teleports.

Mojang can fix the problem in the game, but it's not really possible for a mod to do it any way other than how I've done it. The only way I can see it being fixed by Mojang is modifying the movement packet or implementing another fix.

**Comment by chmonyasik** [comment]
oh okay, thanks!
